# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.26~git
# 

Name:       voicecall-qt5

# >> macros
# << macros

Summary:    Voice Call Suite
Version:    0.4.0
Release:    1
Group:      Communications/Telephony and IM
License:    Apache License, Version 2.0
URL:        http://github.com/nemomobile/voicecall
Source0:    %{name}-%{version}.tar.gz
Source100:  voicecall-qt5.yaml
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Multimedia)
BuildRequires:  pkgconfig(libresourceqt5)
BuildRequires:  pkgconfig(libpulse-mainloop-glib)
BuildRequires:  pkgconfig(ofono-qt5)
BuildRequires:  pkgconfig(TelepathyQt4) >= 0.9.3
BuildRequires:  pkgconfig(TelepathyQt4Farstream)
BuildRequires:  pkgconfig(ngf-qt5)
BuildRequires:  desktop-file-utils

%description
Next Generation Dialer Application for Nemo Mobile

%package core
Summary:    Core voicecall service and libraries
Group:      Communications/Telephony and IM
Requires:   %{name} = %{version}-%{release}
Requires:   voicecall-libs == %{version}-%{release}
Requires:   telepathy-ring

%description core
Core voicecall service executable, core plugins and library

%package devel
Summary:    Voicecall development package
Group:      Communications/Telephony and IM
Requires:   %{name} = %{version}-%{release}
Requires:   voicecall-libs == %{version}-%{release}

%description devel
Voicecall development libraries and headers

%package plugin-ofono
Summary:    Voicecall ofono plugin provider
Group:      Communications/Telephony and IM
Requires:   %{name} = %{version}-%{release}
Requires:   voicecall-core == %{version}-%{release}

%description plugin-ofono
Voicecall manager plugin for using ofono to make and receive calls.

%package libs
Summary:    Core voicecall libraries
Group:      Communications/Telephony and IM
Requires:   %{name} = %{version}-%{release}
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig

%description libs
Core libraries of voicecall

%package ui-reference
Summary:    Voicecall reference QML user interface
Group:      Communications/Telephony and IM
Requires:   %{name} = %{version}-%{release}
Requires:   voicecall-core == %{version}-%{release}
Requires:   tone-generator
Requires:   commhistory-daemon
Requires:   libcommhistory-declarative
Provides:   meego-handset-dialer >= 0.2.4
Provides:   voicecall == %{version}-%{release}
Obsoletes:  meego-handset-dialer < 0.2.4
Obsoletes:  voicecall <= 0.1.5

%description ui-reference
Voicecall reference QML phone application user interface

%package plugin-resource-policy
Summary:    Voicecall plugin for resource policy audio routing
Group:      Communications/Telephony and IM
Requires:   %{name} = %{version}-%{release}
Requires:   voicecall-core == %{version}-%{release}

%description plugin-resource-policy
Voicecall manager plugin for direct resource policy based audio routing and stream control.

%package plugin-pulseaudio
Summary:    Voicecall plugin for pulseaudio interaction
Group:      Communications/Telephony and IM
Requires:   %{name} = %{version}-%{release}
Requires:   voicecall-core == %{version}-%{release}

%description plugin-pulseaudio
Voicecall manager plugin for direct pulseaudio audio routing and stream control.

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre


make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%post libs -p /sbin/ldconfig

%postun libs -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
# >> files
# << files

%files core
%defattr(-,root,root,-)
%{_bindir}/voicecall-manager
%{_libdir}/voicecall-qt5/plugins/libvoicecall-playback-manager-plugin.so
%{_libdir}/voicecall-qt5/plugins/libvoicecall-telepathy-plugin.so
%{_libdir}/voicecall-qt5/plugins/libvoicecall-ngf-plugin.so
%config %{_sysconfdir}/xdg/autostart/voicecall-manager.desktop
%{_libdir}/systemd/user/voicecall-manager.service
# >> files core
# << files core

%files devel
%defattr(-,root,root,-)
%{_libdir}/libvoicecall-qt5.so
# >> files devel
# << files devel

%files plugin-ofono
%defattr(-,root,root,-)
%{_libdir}/voicecall-qt5/plugins/libvoicecall-ofono-plugin.so
# >> files plugin-ofono
# << files plugin-ofono

%files libs
%defattr(-,root,root,-)
%{_libdir}/libvoicecall-qt5.so.1
%{_libdir}/libvoicecall-qt5.so.1.0
%{_libdir}/libvoicecall-qt5.so.1.0.0
%{_libdir}/qt5/imports/stage/rubyx/voicecall/libvoicecall-qt5.so
%{_libdir}/qt5/imports/stage/rubyx/voicecall/qmldir
# >> files libs
# << files libs

%files ui-reference
%defattr(-,root,root,-)
%{_bindir}/voicecall-ui
%{_datadir}/voicecall-ui/qml
%{_datadir}/applications/voicecall-ui.desktop
%config %{_sysconfdir}/xdg/autostart/voicecall-ui-prestart.desktop
%{_libdir}/systemd/user/voicecall-ui-prestart.service
# >> files ui-reference
# << files ui-reference

%files plugin-resource-policy
%defattr(-,root,root,-)
%{_libdir}/voicecall-qt5/plugins/libvoicecall-resource-policy-routing-plugin.so
# >> files plugin-resource-policy
# << files plugin-resource-policy

%files plugin-pulseaudio
%defattr(-,root,root,-)
%{_libdir}/voicecall-qt5/plugins/libvoicecall-pulseaudio-plugin.so
%config %{_sysconfdir}/voicecall/modes.ini
# >> files plugin-pulseaudio
# << files plugin-pulseaudio
